//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullanciId { get; set; }
        public string kullaniciAdi { get; set; }
        public Nullable<int> kullaniciYetki { get; set; }
        public string kullaniciParola { get; set; }
    }
}
